[package]
name = "machine_collector"
version = "0.1.0"
edition = "2024"

[dependencies]
mac_address = "1.1.8"
sysinfo = "0.37.0" 
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
native-tls = "0.2"
postgres = "0.19"
postgres-native-tls = "0.5"